### ISSUE TITLE
最新版v0.3.4无法生成二进制文件

### ISSUE THREAD

**Issue by jemfull** [kafuumi/ltc#1]
我使用的是centos7 go 1.18.2版本，编译0.1.1没问题，但是编译最新版的0.3.4就是输出不了二进制文件，我想把它交叉编译为arm文件以便在我的android机上运行，不知道有没有解决办法？

**Comment by Hami-Lemon** [comment]
最新版和0.1.1在目录结构上有差别，最新版编译输出二进制文件需要在`lrctocaptions`目录中执行编译命令，参考编译命令：

```bash
cd ./lrctocaptions
go build -o ltc .
```

另外，交叉编译只需要设置好`GOOS`，`GOARCH`这两个环境变量就行了。

**Comment by jemfull** [comment]
好的，非常感谢。
